### ISSUE TITLE
DEBUG settings are enabled in production

### ISSUE THREAD

**Issue by SmBe19** [ioi/translation#19]
The settings file sets `DEBUG` to `True`, which should be changed to `False` in production. As far as I can see, this is also not changed in the `automation` repository, so if this is deployed following the documentation, this setting is not changed.

```
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
```

Related, in production the setting `ALLOWED_HOSTS` should be adjusted, maybe this could be added to the documentation.

**Comment by gollux** [comment]
`DEBUG` now defaults to `False`, unless `TRANS_DEBUG=1` is passed in the environment (e.g., via container configuration).
