### ISSUE TITLE
The "additional copy" should list languages, not countries

### ISSUE THREAD

**Issue by wil93** [ioi/translation#3]
Right before submitting translation for printing, there is the option of requesting up to two additional translations. However the "additional copy" is listing countries instead of languages.

Moreover, the fact that an English version is always going to be provided could be made more clear. For example we could use the same "selection" widget, but disabled (as in: cannot be changed from "English")

**Comment by fushar** [comment]
We have implemented this for IOI 2022. Example screenshot:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1525580/188306737-2466d00d-2f38-4aff-913f-408c5703a734.png">

**Comment by niemela** [comment]
Why the underscore? These are IETF language tags (BCP 47), right? There should be an hyphen not an underscore.

**Comment by fushar** [comment]
I also wondered the same but this has been the convention in this app:

https://github.com/ioi/translation/blob/2b1bf11957253088e04ed5eeb7d559030659c401/trans/models.py#L42-L48

When I tried to "fix" this and change the underscore to hyphen, this broke our automation to CMS. When adding a task statement to CMS, somehow it only accepts underscore, not hyphen (to indicate the country). E.g.:

- If we input `id` as language code on admin interface => Contestant interface will show `Indonesian`
- If we input `id_ID` as language code on admin interface => Contestant interface will show `Indonesian (Indonesia)`
- If we input `id-ID` as language code on admin interface => Contestant interface will show `id-ID` (invalid)

So, we kept this as-is.

**Comment by niemela** [comment]
Ok, so this is a CMS bug.

It would probably be a good thing to document somewhere?

**Comment by gollux** [comment]
I guess that the syntax used by CMS was inspired by UNIX locale names, not IETF language tags.

**Comment by niemela** [comment]
Yes, that must be the explanation.

It's still wrong though. We are specifying a language not a locale, those are not exactly the same. Also, some of the language tags we have used have included scrips, which is not allowed in UNIX locales but are in IETF language tags.
